### ISSUE TITLE
Add a newer Node

### ISSUE THREAD

**Issue by jrglee** [revinate-docker/docker-node#1]
We should add a couple of newer images. Preferably some of the 5.x.x series versions

**Comment by vinaykr** [comment]
Should we pin node to a specific version and also match the docker-node version to the node version?

**Comment by alexleigh** [comment]
So this happened: https://github.com/revinate-docker/kube-namespaces/commit/c3075ea44376a0abc7b702435846da80277ff9b5

**Comment by jrglee** [comment]
Is this repo even necessary now?

**Comment by alexleigh** [comment]
Resolved by 234e792985611c4c3ab02658bfb26e8178890d9e
